spring.application.name=backend

spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB

# Local document storage (relative to working directory)
app.files.upload-dir=uploads

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/emp_db
spring.datasource.username=postgres
spring.datasource.password=admin

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Initialize sample data from data.sql
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# JWT
app.jwt.secret=change-this-secret-in-real-projects-change-this-secret
app.jwt.expiration-ms=86400000

# Swagger/OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Mail (Gmail SMTP example)
# IMPORTANT: For Gmail you typically need an App Password (not your normal password).
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mystartup.iteam@gmail.com
spring.mail.password=pehk hipe oppg pfrz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
